### ISSUE TITLE
XML editor become more lagging after using ModelView

### ISSUE THREAD

**Issue by Grieey** [airbnb/epoxy#786] opened 2019-07-17 10:31 UTC
When I create more and more ModelView, the Android studio becoming more and more lagging in the XML editor. After changing to create by ViewHolder, this problem seems to be solved. Is this problem caused by the annotation in ModelView(custom view)? And Is there any way to solve?

**Comment by elihart** [comment] 2019-07-17 13:53
Duplicate of https://github.com/airbnb/epoxy/issues/771

**Closed** 2019-07-22 09:25 UTC
