### ISSUE TITLE
Duplicates are still present with EpoxyController.setGlobalDuplicateFilteringDefault(true)

### ISSUE THREAD

**Issue by TheLester** [airbnb/epoxy#643] opened 2018-12-24 15:13 UTC
I am using MvRx and epoxy together. In one of my fragments there is viewModel with `fragmentViewModel` scope and I'm using `simpleController` from MvRx package.
I've configured epoxy with such method calls:
```
  EpoxyController.setGlobalDuplicateFilteringDefault(true)
        EpoxyController.setGlobalDebugLoggingEnabled(BuildConfig.DEBUG)
        EpoxyController.setGlobalExceptionHandler { controller, exception ->
            Timber.e(exception, controller.javaClass.name)
        }
```
In epoxy conroller I have some items with hardcoded ids, e.g.:
```
override fun epoxyController() = simpleController(viewModel) { 
...
    if (it.myData.isNotEmpty()) {
            detailsHeaderItem {
                id("detail")
                titleRes(R.string.some_res)
            }
        }

        otherIem {
            id("other")
            titleRes(R.string.other_res)
        }
...
}
```
After changing state by using `copy` of State class I have multiple calls of `requestModelBuild`.
After that _sometimes_ I see 2 otherIems instead of 1 (depends on state's myData items count).
 So  `setGlobalDuplicateFilteringDefault(true)` isn't working for this case and there are no exceptions in GlobalExceptionHandler. 

If you need more details, please let me know (cause I can't post the whole source code).
I am pretty sure it's some issue with async diff mechanism of epoxy, rather than issues with MvRX.

**Comment by TheLester** [comment] 2019-01-04 22:35
1) Yes, `filterDuplicatesIfNeeded` is called with `filterDuplicates = true`
2) Nope, I have only one item with "id("other")"


```
override fun epoxyController() = simpleController(viewModel) { 
...
// other items
...
//item with id("other") here
...
// other items
...
}
```

As you can see I'm using simpleController extension function from MvRx sample

```
fun <S : MvRxState, A : MvRxViewModel<S>> BaseFragment.simpleController(
    viewModel: A,
    buildModels: EpoxyController.(state: S) -> Unit
) = MvRxEpoxyController {
    if (view == null || isRemoving) return@MvRxEpoxyController
    withState(viewModel) { state ->
        buildModels(state)
    }
}
```

3)MvRxEpoxyController - is a subclass of `AsyncEpoxyController`, so yes , I'm using async model building and diffing. Data access should be thread safe because withState block of my view should run synchronously and state - is immutable kotlin's data class:

```
/**
 * Accesses ViewModel state from a single ViewModel synchronously and returns the result of the block.
 */
fun <A : BaseMvRxViewModel<B>, B : MvRxState, C> withState(viewModel1: A, block: (B) -> C) = block(viewModel1.state)
```

4)As I can see - it's permanent, duplicate items are shown immidiately after I've launched screen.

What I've noticed - I have frequent calls of
```  
  override fun invalidate() {
        epoxyRecyclerView().requestModelBuild()
    }
```
, some of them with delay between them of few milliseconds. I tried to set breakpoint for `epoxyRecyclerView().requestModelBuild()` and after resuming them one after another - there were no duplicates.

It's possible that current issue and issue https://github.com/airbnb/epoxy/issues/652 have a common problem.

**Comment by elihart** [comment] 2019-01-04 22:59
Thanks for the update - my suspicion is that there is an issue with async diffing and race conditions. Can you disable async diffing and see if the issue persists? if it persists, can you try disabling both async model building and diffing and check if it persists again?

Given that you're not feeding duplicate models I'm not sure where the duplicates are coming from. My first guess is that there is an issue in the diffing - possibly a threading issue since it seems to manifest with quick updates.

In EpoxyControllerAdapter can you verify that `setModels` is passed the correct list of models?

Then can you debug the diff results that come back in `onResult`?

**Comment by elihart** [comment] 2019-01-12 16:47
@TheLester were you able to find any more details through debugging?

**Comment by TheLester** [comment] 2019-01-13 18:40
@elihart Hi, sorry for the delay. So after debugging, I can say that:
- disabling async diffing (by using `AsyncEpoxyController(true, false)` and disabling async model building (by using `AsyncEpoxyController(false, false)`) didn't solve the issue, it persists.

As for `setModels` and `onResult` .
I put logging breakpoint into 
`
  void setModels(@NonNull ControllerModelList models) {
    differ.submitList(models);
  }
` 
and print the result of `models` into console. `onResult` has same results as `setModels`
I made a visual representation of what I've noticed:

<img width="241" alt="untitled diagram xml - draw io 2019-01-13 20-29-31" src="https://user-images.githubusercontent.com/6323430/51089233-85cc9a80-1772-11e9-929d-f7f542bed0e3.png">

Cells with the same colors are models with the same ids and data.

As I can see, for some reason, models from the first model build stayed in the adapter, and after the second model build, new data didn't replace old one, even if models share same id and they are equal.

**Comment by elihart** [comment] 2019-01-14 21:43
Thanks for the update and the debugging information.

The other person having an issue with duplicates (https://github.com/airbnb/epoxy/issues/652) seems to have realized that the issue is in their data structure, and that it is being incorrectly modified.

Since you verified that `onResult` and `setModels` have the same data, and the issues persists when async model building and diffing are disabled, the issue must be from the model building stage.

Is there any chance that your model building function is referencing old or incorrect data, or is your data getting merged somehow?

Could you share all of your `simpleController` and I could look through it for potential issues?

**Comment by TheLester** [comment] 2019-01-17 14:08
It would be better to create a demo with this bug, I'll implement it

**Closed** 2020-09-17 14:34 UTC
