### ISSUE TITLE
Usage within Android Library modules

### ISSUE THREAD

**Issue by conanchen** [airbnb/epoxy#226] opened 2017-06-07 03:15 UTC
I just moved an epoxy model  "MessageIssueModel" from app module  into an Android library project say "sample-library"
```
import library.sample.R;
@EpoxyModelClass(layout = R.layout.message_item_model)
public abstract class MessageIssueModel extends EpoxyModel<MessageIssueView> {
    @EpoxyAttribute
    String title;
}
```
also i moved all related xml file into sample-library e.g. layout/message_item_model.xml . 
Android studio will complain that R.layout.message_item_model _Attribute value must be constant_. 
That cause the MessageIssueModel_ will not be generated automatically.

in my smaple-library's build.gradle i try 2.0,0 and 2.1.0, the same compile problem.

**Comment by elihart** [comment] 2017-06-07 21:46
This is an issue with all annotations that take resources as parameters (eg butterknife).

Once you are using modules the R classes for each module are not final and their values change after the modules are all merged together. The error message happens because annotation parameters must be final.

Butterknife solved this first by using a gradle plugin to generate an `R2` class, which is a duplicate of R, but with final values. There are other ways you could get around it, but we prefer to just apply the butterknife gradle plugin and use R2 values in the annotation.

Let me know if you want more information than that.

**Comment by conanchen** [comment] 2017-06-08 08:23
thanks @elihart , 

I have Butternife to generate R2 for the elements of layout, but not the layout, the layout id is still 
R.layout.message_item_model .  I trid another way without @EpoxyModelClass annotation
`import library.sample.R;
import library.sample.R2;
public class MessageIssueModel extends EpoxyModel<MessageIssueView> {
    @EpoxyAttribute
    String title;
 
   @Override
   protected int getDefaultLayout(){
       return R.layout.message_item_model ;
  }
}`

now the MessageIssueModel_ is generated, and Android studio seems happy ,  but when i tried to deploy app and got compile error:

**com.airbnb.epoxy.EpoxyProcessorException: Epoxy model class must be abstract (MessageIssueModel )**

Appreciated if you can share an example to work around this .

**Comment by conanchen** [comment] 2017-06-08 09:07
ok, finally got it, refer to below code:

```
import library.sample.R;
import library.sample.R2;
**@EpoxyModelClass**
**public abstract** class MessageIssueModel extends EpoxyModel<MessageIssueView> {
    @EpoxyAttribute
    String title;
 
   @Override
   protected int getDefaultLayout(){
       return R.layout.message_item_model ;
  }
}
```

**Comment by geralt-encore** [comment] 2017-06-08 09:30
@conanchen `getDefaultLayout` can be omitted as well in favour of `@EpoxyModelClass(R.layout.message_item_model)`

**Comment by elihart** [comment] 2017-06-08 14:16
I forgot one important thing, the plug-in doesn't currently support layout
files so we had to modify it. We have our own Fork to do this, but are
trying to get the change pushed to butter knife directly and are waiting
for it to be merged.

https://github.com/JakeWharton/butterknife/pull/969

**Comment by elihart** [comment] 2017-06-08 18:04
I also created this issue a while back https://github.com/JakeWharton/butterknife/issues/871 but Jake Wharton didn't seem to have much interest in it. My coworker recently put up another PR that fixed failing tests so hopefully this one is more likely to be merged...

In the mean time, if anybody wants to either host a public fork of butterknife with the change, or extract the plugin into a dedicated library, I'd be happy to update the Epoxy docs to mention it. Our internal fork is privately hosted unfortunately, and unless I get some extra free time I'm not planning on making it public.

**Comment by yumcoder-platform** [comment] 2017-06-27 20:29
my code is show blew but it is not any effecte.

```
@EpoxyModelClass
public abstract class ImageButtonModel extends EpoxyModel<ImageButtonModel.ImageButtonHolder> {
    @EpoxyAttribute @DrawableRes int imageRes;
    @EpoxyAttribute(DoNotHash) OnClickListener clickListener;

    @Override
    protected int getDefaultLayout() {
        return R.layout.model_button_image;
    }

    @Override
    public void bind(ImageButtonHolder holder) {
        holder.button.setImageResource(imageRes);
        holder.button.setOnClickListener(clickListener);
    }

    @Override
    public void unbind(ImageButtonHolder holder) {
        // Release resources and don't leak listeners as this view goes back to the view pool
        holder.button.setOnClickListener(null);
        holder.button.setImageDrawable(null);
    }

    public static class ImageButtonHolder extends YumcoderHolder {
        @BindView(R2.id.button)
        ImageView button;
    }
}
```

**Comment by elihart** [comment] 2017-06-27 22:26
@yumcoder-platform this shouldn't be related to library projects. can you open a new issue? Are you sure you have the annotation processor defined correctly in your build.gradle file?

**Comment by elihart** [comment] 2017-07-05 17:11
https://github.com/JakeWharton/butterknife/issues/871 was merged a few days ago, so it will probably be available soon in a 8.70 Butterknife release. When it is I'll update the Epoxy docs to make it clear to use the butterknife plugin

**Comment by elihart** [comment] 2017-07-07 15:27
Butterknife 8.7.0 was released with the updated R2 gradle plugin. that should work for everybody needing library project support

**Comment by elihart** [comment] 2017-07-07 15:36
I've updated the readme with instrustructions on using the plugin for library projects https://github.com/airbnb/epoxy/blob/master/README.md#library-projects

**Closed by elihart** 2017-07-07 15:36 UTC
