### ISSUE TITLE
How to Update the model to trigger a view change.

### ISSUE THREAD

**Issue by doomtrooper** [airbnb/epoxy#650] opened 2019-01-01 11:51 UTC
I am using a `OnModelClickListener` to add click listener on an imageView. I want to change the image when the view is clicked. I m little confused on how to achieve the same. How to change the underlying model data? Also, I don't want to fetch all the data again. Should I change the image from the clicklistener itself? I am using a `PagedListEpoxyController`. I don't want to re-fetch the data again from the `repository`.
```
override fun onClick(model: ItemCustomViewModel_?, parentView: ItemCustomView?, clickedView: View?, position: Int) {
        val userName = model!!.post().publishedBy.userName
        emmiter(if (model.post().publishedBy.following) FollowEvent(userName) else UnFollowEvent(userName))
    }
```

**Comment by doomtrooper** [comment] 2019-01-03 09:50
@elihart Can you please help here.

**Comment by elihart** [comment] 2019-01-03 17:24
You generally don't want to change the view directly from the click listener - the model should be rebuilt and diffed, and the changes will be applied to the view.

The `PagedListEpoxyController` changes things though, since it maintains a model cache and doesn't rebuild models created from the paged list - it was designed for the model to get all of it's data from the paged list, and for data changes to only go through the the paged list, in which case models are automatically rebuilt when data changes.

If you need to force the model to be rebuilt with outside data then I think you will need this - PagedListEpoxyController

**Comment by doomtrooper** [comment] 2019-01-04 01:58
> If you need to force the model to be rebuilt with outside data then I think you will need this - PagedListEpoxyController

Did you want to mention something else, since `PagedListEpoxyController` is already merged?

**Comment by elihart** [comment] 2019-01-04 15:44
right, sorry I pasted the wrong thing. 

there is a PR to allow force rebuilding all models - https://github.com/airbnb/epoxy/pull/586

**Comment by elihart** [comment] 2019-01-12 16:45
The pr to force clearing the model cache is merged

**Closed by elihart** 2019-01-12 16:45 UTC
