### ISSUE TITLE
MotionLayout animation issue with Epoxy

### ISSUE THREAD

**Issue by roncbird** [airbnb/epoxy#1021] opened 2020-07-17 00:40 UTC
I've ran into an issue while trying to animate a view in Epoxy using MotionLayout. You can see in the video below, that the views inside the `CardView` animate just fine, but the `CardView` its self does not collapse. 

![animation-issue](https://user-images.githubusercontent.com/6894360/87734356-a0306b80-c78f-11ea-98d0-e50f7b478e75.gif)

Here is how I am trying to get it to behave in Epoxy. The video below is just a simple test app that has one Activity and one layout. The `MotionLayout` animation works as expected if not inflated by Epoxy. 

![working-animation](https://user-images.githubusercontent.com/6894360/87734571-3c5a7280-c790-11ea-8a81-ea1323505ba6.gif)

Here is how the layout `epoxy_activate_card.xml` is set up:

```
<?xml version="1.0" encoding="utf-8"?>
<layout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    xmlns:tools="http://schemas.android.com/tools">

    <data>

        <variable
            name="onActionButtonClicked"
            type="android.view.View.OnClickListener" />

        <variable
            name="onNotReceivedClicked"
            type="me.saket.bettermovementmethod.BetterLinkMovementMethod.OnLinkClickListener" />

        <variable
            name="onChevronClicked"
            type="android.view.View.OnClickListener" />

    </data>

    <com.google.android.material.card.MaterialCardView
        android:id="@+id/cardView"
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:layout_margin="@dimen/content_padding"
        app:cardElevation="8dp"
        app:cardCornerRadius="4dp"
        android:animateLayoutChanges="true">

        <androidx.constraintlayout.motion.widget.MotionLayout
            android:id="@+id/motionLayout"
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            android:layout_margin="@dimen/content_padding"
            app:layoutDescription="@xml/card_activation_motion_scene">

            <TextView
                android:id="@+id/title"
                android:layout_width="0dp"
                android:layout_height="wrap_content"
                android:layout_marginStart="10dp"
                android:layout_marginEnd="16dp"
                android:text="@string/accounts_card_shipped_title"
                android:textAppearance="?textAppearanceHeadline6"
                app:autoSizeTextType="uniform"
                app:layout_constraintEnd_toEndOf="parent"
                app:layout_constraintStart_toStartOf="parent"
                app:layout_constraintTop_toTopOf="parent" />

            <ImageView
                android:id="@+id/chevron"
                android:layout_width="wrap_content"
                android:layout_height="wrap_content"
                android:layout_marginTop="@dimen/debit_card_active_top_margin"
                android:onClick="@{onChevronClicked}"
                android:src="@drawable/ic_chevron_up"
                app:layout_constraintEnd_toEndOf="parent" />

            <ImageView
                android:id="@+id/cardImage"
                android:layout_width="128dp"
                android:layout_height="200dp"
                android:layout_marginTop="@dimen/debit_card_active_top_margin"
                android:scaleType="fitXY"
                android:src="@drawable/ic_debit_card"
                app:layout_constraintStart_toStartOf="parent"
                app:layout_constraintEnd_toEndOf="parent"
                app:layout_constraintTop_toBottomOf="@+id/title" />

            <com.google.android.material.button.MaterialButton
                android:id="@+id/actionButton"
                android:layout_width="0dp"
                android:layout_height="wrap_content"
                android:layout_marginTop="@dimen/debit_card_active_top_margin"
                android:gravity="center"
                android:onClick="@{onActionButtonClicked}"
                android:text="@string/accounts_card_activate_card"
                app:layout_constraintEnd_toEndOf="parent"
                app:layout_constraintStart_toStartOf="parent"
                app:layout_constraintTop_toBottomOf="@id/cardImage"/>

            <com.google.android.material.textview.MaterialTextView
                android:id="@+id/deliveryMessage"
                android:layout_width="wrap_content"
                android:layout_height="wrap_content"
                android:layout_marginTop="8dp"
                android:gravity="center"
                android:text="@string/accounts_card_delivery_message"
                android:textAppearance="?textAppearanceCaption"
                app:layout_constraintEnd_toEndOf="parent"
                app:layout_constraintStart_toStartOf="parent"
                app:layout_constraintTop_toBottomOf="@+id/actionButton" />

            <com.google.android.material.textview.MaterialTextView
                android:id="@+id/contactUs"
                android:layout_width="0dp"
                android:layout_height="wrap_content"
                android:layout_marginTop="8dp"
                android:gravity="center"
                app:onLinkClicked="@{onNotReceivedClicked}"
                app:spannedText="@{@string/accounts_card_havent_received}"
                app:shouldBoldSpan="@{false}"
                android:textAppearance="?textAppearanceCaption"
                app:layout_constraintEnd_toEndOf="parent"
                app:layout_constraintStart_toStartOf="parent"
                app:layout_constraintTop_toBottomOf="@+id/deliveryMessage"
                app:layout_constraintBottom_toBottomOf="parent"
                tools:text="Haven't Received it?"/>

        </androidx.constraintlayout.motion.widget.MotionLayout>

    </com.google.android.material.card.MaterialCardView>

</layout>
```

I'm not sure if `card_activation_motion_scene.xml` is needed, but I'll add it here to provide a more thorough context:

```
<?xml version="1.0" encoding="utf-8"?>
<MotionScene xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    xmlns:motion="http://schemas.android.com/apk/res-auto">

    <Transition
        motion:constraintSetEnd="@+id/end_set"
        motion:constraintSetStart="@+id/starting_set"
        motion:duration="500" />

    <ConstraintSet android:id="@+id/starting_set" />

    <ConstraintSet android:id="@+id/end_set">
        <Constraint android:id="@+id/chevron">
            <Transform android:rotation="-180" />
        </Constraint>
        <Constraint android:id="@+id/cardImage">
            <Transform
                android:scaleX="0"
                android:scaleY="0" />
            <PropertySet android:visibility="gone" />
        </Constraint>
        <Constraint android:id="@+id/actionButton">
            <Transform
                android:scaleX="0"
                android:scaleY="0" />
            <PropertySet android:visibility="gone" />
        </Constraint>
        <Constraint
            android:id="@+id/deliveryMessage"
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            android:layout_marginStart="10dp"
            android:layout_marginTop="4dp"
            motion:layout_constraintStart_toStartOf="parent"
            motion:layout_constraintTop_toBottomOf="@+id/title"/>
        <Constraint android:id="@+id/contactUs">
            <PropertySet android:visibility="gone" />
        </Constraint>
    </ConstraintSet>

</MotionScene>
```

Then in `AccountsFragment` I'm doing this:

```Kotlin
override fun epoxyController() = simpleController(viewModel) { state ->

   ....

   activateCard {
                id("Activate Card CTA")
                onChevronClicked { _ ->
                    if (chevron.rotation == -180f) {
                        motionLayout.transitionToStart()
                        viewModel.setIsCardCollapsed(false)
                    } else {
                        motionLayout.transitionToEnd()
                        viewModel.setIsCardCollapsed(true)
                    }
                }
   }

   ....

}
```

I tried using a custom view annotated with `@ModelView()`, and `@ModelProp`s, but I couldn't get that to work properly either. I'm not sure how to get my Design team's requested animation working with Epoxy, so I was hoping to get some suggestions from the MvRx/Epoxy community that would point me in the right direction. Any help is much appreciated. Thanks in advance.

**Comment by rohithThammaiah** [comment] 2020-07-18 16:17
Possible Duplicate of #663

**Comment by roncbird** [comment] 2020-07-20 14:14
@rohithThammaiah Thanks for the comment. I'll give it try and comment on whether it works or not.

**Comment by roncbird** [comment] 2020-07-20 22:50
Unfortunately, the suggestions in #663, did not work. I tried this 

`ActivateCardRow.kt`

```
@ModelView(autoLayout = Size.MATCH_WIDTH_WRAP_HEIGHT)
class ActivateCardRow @JvmOverloads constructor(
    context: Context,
    attrs: AttributeSet? = null,
    defStyleAttr: Int = 0
) : ConstraintLayout(context, attrs, defStyleAttr) {

    init {
        inflate(context, R.layout.view_activate_card, this)
    }

    @CallbackProp
    fun onClick(listener: OnClickListener?) {
        chevron.setOnClickListener(listener)
    }

    @AfterPropsSet
    fun useProps() {
    }
}
```

`AccountsFragment.kt`

```
 @Suppress("ComplexMethod")
    override fun epoxyController() = simpleController(viewModel) { state ->

....

activateCardRow {
                id("activate card cta")
                onClick { _ ->
                    if (chevron.rotation == 0f) {
                        motionLayout.transitionToEnd()
                    } else {
                        motionLayout.transitionToStart()
                    }
                }
            }

....

}

```

**Comment by eagskunst** [comment] 2020-07-21 22:25
I have done a collapse/expand animation without MotionLayout. Maybe that can fill your needs? The 'hacky' thing arround it is that the expandable zone layout height is initially 0, and if clicked is updated to wrap content (and viceversa). I used a ModelView and implemented the clickListener inside the View class. Happy to share some code if you are interested in.

**Comment by roncbird** [comment] 2020-07-22 16:15
@eagskunst I appreciate your response and offer to share code. One of our lead devs was able to find a solution though while still being able to use the `MotionLayout`. We did something similar found in this blog post https://coderwall.com/p/35xi3w/layout-change-animations-sliding-height. 

Here are the important bits:

```
class SlideAnimation(
        var view: View,
        var fromHeight: Int,
        var toHeight: Int
) : Animation() {

    override fun applyTransformation(interpolatedTime: Float, transformation: Transformation?) {
        if (view.height != toHeight) {
            val newHeight = (fromHeight + (toHeight - fromHeight) * interpolatedTime).toInt()
            view.layoutParams.height = newHeight
            view.requestLayout()
        }
    }

    override fun willChangeBounds(): Boolean {
        return true
    }
}
```

```
 override fun epoxyController() = simpleController(viewModel) { state ->

....

activateCard {
                id("Activate Card CTA")
                onChevronClicked { view ->
                    val card = view.findParentOfType<CardView>()

                    val collapsedHeight = resources.getDimensionPixelSize(R.dimen.activate_card_collapsed_height)
                    val expandedHeight = resources.getDimensionPixelSize(R.dimen.activate_card_expanded_height)

                    val animation = if (view.rotation == -180f) {
                        motionLayout.transitionToStart()
                        card?.let { SlideAnimation(it, collapsedHeight, expandedHeight) }
                    } else {
                        motionLayout.transitionToEnd()
                        card?.let { SlideAnimation(it, expandedHeight, collapsedHeight) }
                    }
                    animation?.let {
                        it.duration = 400
                        // set correct interpolator here to match the motion layout
                        it.interpolator = LinearInterpolator()
                        card?.animation = it
                        card?.startAnimation(it)
                    }
            }

![expand-collapse-animatino-with-e](https://user-images.githubusercontent.com/6894360/88200973-1dcb0000-cc04-11ea-9f0c-8616afeeb2f9.gif)

**Closed** 2020-07-22 16:28 UTC
