### ISSUE TITLE
Unable to override setItemSpacingPx

### ISSUE THREAD

**Issue by blazeroni** [airbnb/epoxy#782] opened 2019-07-12 20:57 UTC
Our app has a Carousel which uses a `StaggeredGridLayoutManager`.  Previously, we had been overriding `setItemSpacingPx` to apply an appropriate item decoration that works with that layout manager.  However, with the conversion to Kotlin the method has become final.

The quick fix would be to allow overriding `setItemSpacingPx` again, but I'm open to other possibilities.  Is there a better way to get decoration for a `StaggeredGridLayoutManager` working?

**Comment by elihart** [comment] 2019-07-15 14:53
Duplicate of https://github.com/airbnb/epoxy/issues/779, although that is closed now.

if you are subclassing Carousel, then you can add any annotated prop function you want, like `setStaggeredItemSpacing` and add your decorator there.

Or you can set an `onBind` callback on your model, but that would have to be done each place the model is used.

I am open to making setItemSpacingPx if you want to submit a PR

**Comment by elihart** [comment] 2019-10-21 16:09
Merged #829

**Closed by elihart** 2019-10-21 16:09 UTC
