### ISSUE TITLE
Reproducible - Exception after checking checkbox and scroll - Could not find RecyclerView holder for clicked view

### ISSUE THREAD

**Issue by premkumarroyal** [airbnb/epoxy#821] opened 2019-09-10 19:41 UTC
I Have a checkbox in my layout if I check the checkbox and scroll the layout I am getting 
`java.lang.IllegalStateException: Could not find RecyclerView holder for clicked view`

```
<?xml version="1.0" encoding="utf-8"?>
<layout xmlns:android="http://schemas.android.com/apk/res/android">
    <data>
        <variable
            name="name"
            type="String" />
        <variable
            name="onCheckChange"
            type="android.widget.CompoundButton.OnCheckedChangeListener" />
        <variable
            name="isSelected"
            type="Boolean" />
    </data>

    <LinearLayout
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:orientation="vertical">

        <CheckBox
            android:id="@+id/checkBox"
            android:layout_width="50dp"
            android:layout_height="50dp"
            android:layout_marginStart="8dp"
            android:layout_marginTop="8dp"
            android:checked="@{isSelected}"
            android:onCheckedChanged="@{onCheckChange}"
            android:text="@{name}" />
    </LinearLayout>
</layout>
```

    class CheckBoxExActivity : AppCompatActivity() {

    lateinit var recyclerView: EpoxyRecyclerView
    var checkBoxList = mutableListOf<CheckBoxData>()
    override fun onCreate(savedInstanceState: Bundle?) {

        super.onCreate(savedInstanceState)
        setContentView(R.layout.activity_main)
        fillCheckBox()
        recyclerView = findViewById(R.id.epoxy_list)
        recyclerView.layoutManager = LinearLayoutManager(baseContext)
        recyclerView.withModels {
            for (item in checkBoxList) {
                checkBoxLayout {
                    Log.d("Prem", "${item.id}")
                    id(item.id)
                    name(item.id.toString())
                    isSelected(item.isSelected)
                    onCheckChange { model, parentView, checkedView, isChecked, position ->
                        checkBoxList[position].isSelected = isChecked
                    }
                }
            }
        }
    }

    fun fillCheckBox(): MutableList<CheckBoxData> {
        for (i in 1..50) {
            checkBoxList.add(CheckBoxData(i))
        }
        return checkBoxList
    }
}

data class CheckBoxData(var id: Int, var isSelected: Boolean = false)

After checking the checkbox and scrolling getting an exception.

StackTrace:

```
2019-09-11 01:05:53.357 11765-11765/com.we.epoxysample E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.we.epoxysample, PID: 11765
    java.lang.IllegalStateException: Could not find RecyclerView holder for clicked view
        at com.airbnb.epoxy.WrappedEpoxyModelCheckedChangeListener.onCheckedChanged(WrappedEpoxyModelCheckedChangeListener.java:31)
        at android.widget.CompoundButton.setChecked(CompoundButton.java:171)
        at androidx.databinding.adapters.CompoundButtonBindingAdapter.setChecked(CompoundButtonBindingAdapter.java:44)
        at com.we.epoxysample.databinding.EpoxyCheckBoxLayoutBindingImpl.executeBindings(EpoxyCheckBoxLayoutBindingImpl.java:136)
        at androidx.databinding.ViewDataBinding.executeBindingsInternal(ViewDataBinding.java:472)
        at androidx.databinding.ViewDataBinding.executePendingBindings(ViewDataBinding.java:444)
        at com.airbnb.epoxy.DataBindingEpoxyModel.bind(DataBindingEpoxyModel.java:50)
        at com.airbnb.epoxy.DataBindingEpoxyModel.bind(DataBindingEpoxyModel.java:36)
        at com.airbnb.epoxy.EpoxyViewHolder.bind(EpoxyViewHolder.java:61)
        at com.airbnb.epoxy.BaseEpoxyAdapter.onBindViewHolder(BaseEpoxyAdapter.java:98)
        at com.airbnb.epoxy.BaseEpoxyAdapter.onBindViewHolder(BaseEpoxyAdapter.java:15)
        at androidx.recyclerview.widget.RecyclerView$Adapter.bindViewHolder(RecyclerView.java:7098)
        at androidx.recyclerview.widget.RecyclerView$Recycler.tryBindViewHolderByDeadline(RecyclerView.java:6010)
        at androidx.recyclerview.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:6277)
        at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:6116)
        at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:6112)
        at androidx.recyclerview.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:2303)
        at androidx.recyclerview.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1627)
        at androidx.recyclerview.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1587)
        at androidx.recyclerview.widget.LinearLayoutManager.scrollBy(LinearLayoutManager.java:1391)
        at androidx.recyclerview.widget.LinearLayoutManager.scrollVerticallyBy(LinearLayoutManager.java:1128)
        at androidx.recyclerview.widget.RecyclerView.scrollStep(RecyclerView.java:1841)
        at androidx.recyclerview.widget.RecyclerView$ViewFlinger.run(RecyclerView.java:5300)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:911)
        at android.view.Choreographer.doCallbacks(Choreographer.java:723)
        at android.view.Choreographer.doFrame(Choreographer.java:655)
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:897)
        at android.os.Handler.handleCallback(Handler.java:790)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6494)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
```

**Comment by elihart** [comment] 2019-09-10 21:43
Duplicate of https://github.com/airbnb/epoxy/issues/797

**Closed by elihart** 2019-09-10 21:43 UTC
