### ISSUE TITLE
@Nullable annotation breaks build

### ISSUE THREAD

**Issue by charlesx2013** [airbnb/epoxy#273] opened 2017-09-01 23:07 UTC
![image](https://user-images.githubusercontent.com/5563367/29990444-7874d194-8f2f-11e7-9633-227bb5862677.png)

causes this error:

```java
stderr: /Users/charles_xue/CS/apps/android/buck-out/annotation/n2/core/__src_release_gen__/com/n2/components.SimpleSectionModel_.java:100: error: reference to setBodyItem is ambiguous
      object.setBodyItem(null);
            ^
  both method setBodyItem(java.lang.CharSequence) in com.n2.components.SimpleSection and method setBodyItem(java.util.List<java.lang.CharSequence>) in com.n2.components.SimpleSection match
/Users/charles_xue/CS/apps/android/buck-out/annotation/n2/core/__src_release_gen__/com/n2/components.SimpleSectionModel_.java:149: error: reference to setBodyItem is ambiguous
        object.setBodyItem(null);
              ^
  both method setBodyItem(java.lang.CharSequence) in com.n2.components.SimpleSection and method setBodyItem(java.util.List<java.lang.CharSequence>) in com.n2.components.SimpleSection match
/Users/charles_xue/CS/apps/android/n2/core/src/main/java/com/n2/primitives/ImpactDisplayCardContentContainer.java:-1: note: Some input files use or override a deprecated API.
```

Removing the @Nullable annotation fixes this problem.

**Comment by elihart** [comment] 2017-09-03 18:31
Upon further inspection I think this is a duplicate of https://github.com/airbnb/epoxy/issues/272

**Closed by elihart** 2017-09-03 18:31 UTC
