### ISSUE TITLE
Cannot be  Use android.support.v4.widget.SwipeRefreshLayout

### ISSUE THREAD

**Issue by yuhanghate** [airbnb/epoxy#92] opened 2016-12-27 15:51 UTC
Cannot be  Use android.support.v4.widget.SwipeRefreshLayout, Loading Progressbar not show
p.
I'm if replace RecyclerView and RecyclerView.Adapter model,When  Drop Down  Can mormally Display
please my Help

**Comment by elihart** [comment] 2016-12-29 11:20
Do you have a hidden model as your first model? If so I believe this is a duplicate of https://github.com/airbnb/epoxy/issues/74

**Closed** 2017-01-03 04:41 UTC
