### ISSUE TITLE
paged list does not work properly

### ISSUE THREAD

**Issue by yigit** [airbnb/epoxy#524] opened 2018-09-04 16:14 UTC
Trying to use epoxy paged list controller results in broken scrolling + weird artifacts.

I didn't dig deeper to figure out what is wrong but using the same data source with paged list adapter works fine but using epoxy paged list controller creates awkward artifacts while scrolling, cannot load more data etc.

In the attached video, you can observe that it loads more items then loses them.

I've also attached a project that reproduces the error. You can replace `useEpoxy` with use `usePagedList` in `onCreate` to see the expected behavior.

[EpoxyPagedListBug.tar.gz](https://github.com/airbnb/epoxy/files/2349373/EpoxyPagedListBug.tar.gz)
[epoxy-paged-list-bug.webm.tar.gz](https://github.com/airbnb/epoxy/files/2349378/epoxy-paged-list-bug.webm.tar.gz)

**Comment by shakil807g** [comment] 2018-09-04 17:33
It great to see  @yigit  using epoxy but it's funny at the same time i mean havn't you behind recyclerview :)

**Comment by yigit** [comment] 2018-09-04 19:48
Sure I am and i love using stuff that people create on top of the libraries we write. We certainly cannot write everything :)

**Comment by elihart** [comment] 2018-09-06 12:49
I've talked to Yigit externally about this, my initial thought was that the page size was not large enough, but it seems this may be an actual bug.

I haven't prioritized working on PagedList as we don't use it ourselves and I don't know if other people do.

**Comment by JasonHezz** [comment] 2018-09-06 19:41
May be this is duplicate of https://github.com/airbnb/epoxy/issues/464?
I rollback to version 2.11.0 and debug, issue maybe in **buildModels** method
In version 2.11.0, once pageList changed, **last


BuiltLowerBound** is always 0 and  **lastBuiltUpperBound** is always list.size()
so I copy a 2.12.0 version, change following code
```
buildModels(list.subList(lastBuiltLowerBound, lastBuiltUpperBound));
```
to 
```
buildModels(list);
```
I attached a project to help you test

[EpoxyPagedListBug.zip](https://github.com/airbnb/epoxy/files/2358498/EpoxyPagedListBug.zip)

**Comment by elihart** [comment] 2018-10-18 14:54
This is addressed with the new PagedListEpoxyController

**Closed by elihart** 2018-10-18 14:54 UTC
